# Uncomment the next line to define a global platform for your project
#platform :ios, '9.0'

target 'FWSideMenu' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
  
  # 侧滑关闭页面：https://github.com/forkingdog/FDFullscreenPopGesture
  pod 'FDFullscreenPopGesture'
  pod 'ZLPhotoBrowser'
  pod 'SwipeableTabBarController'
  pod 'Alamofire', '~> 5.2'
  pod 'SQLite.swift', '~> 0.12.0'
  pod 'LXPhotosManager'
  pod 'DateTimePicker'
  pod 'SwiftDate', '~> 5.0'
  pod 'Kingfisher/SwiftUI'
  #pod 'SwiftyComments', :git => 'https://github.com/tsucres/SwiftyComments.git'
 # pod 'SwiftyComments'
  pod 'SwipeCellKit'
  pod 'SelectableTextView', '~> 1.0.2'
  pod 'MMKV'
  pod 'AYPopupPickerView'
  pod 'ZLaunchAd'
  pod 'YYText', '~> 1.0.5'
  pod 'SnapKit'
end
